# Generated by Django 5.2.12 on 2026-03-25 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(help_text="Week range, e.g., '07th Feb - 13th Feb'", max_length=50)),
                ('video_drive_target', models.IntegerField(default=0)),
                ('video_drive_achieved', models.IntegerField(default=0)),
                ('video_drive_shortfall', models.IntegerField(default=0)),
                ('travel_mobile_target', models.IntegerField(default=0)),
                ('travel_mobile_achieved', models.IntegerField(default=0)),
                ('travel_mobile_shortfall', models.IntegerField(default=0)),
                ('mca_sourcing_target', models.IntegerField(default=0)),
                ('mca_sourcing_achieved', models.IntegerField(default=0)),
                ('mca_sourcing_shortfall', models.IntegerField(default=0)),
                ('total_target', models.IntegerField(default=0)),
                ('total_achieved', models.IntegerField(default=0)),
                ('total_shortfall', models.IntegerField(default=0)),
                ('shortfall_percentage', models.FloatField(default=0.0, help_text='Shortfall percentage, e.g., -80')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
