# Generated by Django 5.2.12 on 2026-03-25 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklydelivery',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='weeklydelivery',
            name='week',
        ),
        migrations.AddField(
            model_name='weeklydelivery',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='End date of the week (Friday)'),
        ),
        migrations.AddField(
            model_name='weeklydelivery',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Start date of the week (Monday)'),
        ),
    ]
