# Generated by Django 5.2.12 on 2026-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_weeklydeliverysecondary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDeliveryStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(help_text='Phase (e.g., Phase 1, Phase 2)', max_length=100)),
                ('planned_delivery_date', models.DateField(help_text='Planned Delivery Date')),
                ('planned_delivery_count', models.IntegerField(help_text='Planned Delivery count')),
                ('actual_delivery_date', models.DateField(blank=True, help_text='Actual Delivery Date', null=True)),
                ('actual_delivery_count', models.IntegerField(default=0, help_text='Actual Delivery count')),
                ('no_of_weeks_from_last_delivery', models.IntegerField(blank=True, help_text='No of weeks from last delivery', null=True)),
                ('total_new_poi_delivery_till_date', models.IntegerField(default=0, help_text='Total New POI Delivery till date')),
                ('new_poi_inventory_not_delivered', models.IntegerField(default=0, help_text='New POI Inventory (not delivered to client) as on date')),
                ('comments', models.TextField(blank=True, help_text='Comments', null=True)),
                ('type_of_data', models.CharField(blank=True, help_text='Type of data (e.g., Drive Coding-51492)', max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Client Delivery Status',
                'verbose_name_plural': 'Client Delivery Statuses',
                'ordering': ['-planned_delivery_date'],
            },
        ),
    ]
